// <auto-generated />
namespace A3DBhavCopy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class A3DBhavCopyData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A3DBhavCopyData));
        
        string IMigrationMetadata.Id
        {
            get { return "201912240806356_A3DBhavCopyData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
